[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
# Since Build Context is /, these paths are relative to the root
onlyIncludeFiles = [
  "frontend/package.json",
  "frontend/package-lock.json",
  "shared/"
]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]