[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
# All paths are now relative to the root /
onlyIncludeFiles = [
  "frontend/package.json",
  "frontend/package-lock.json",
  "shared/"
]
cmds = ["cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]