# Application name
spring.application.name=cnfpc_full_stack_project_assignment

# Server Configuration
server.port=${PORT:8080}

# PostgreSQL Configuration (using environment variables)
# spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/service_desk}
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://192.168.76.112:5432/service_desk}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:root}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson Configuration for Enum handling
spring.jackson.datatype.enum.read-unknown-enum-values-as-null=true

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.enabled=true

# # Production settings
# spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=${JWT_SECRET:LyH3Dkj4HamburgerHamburgerHamCheeseburgerCheeseburgerBigMacBigMacWhopperWhopper5TprvzStfsB6tn00R3}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Application-specific settings
app.seed-data.sample=true

# Gemini AI Configuration
gemini.enabled=${GEMINI_ENABLED:false}
gemini.api.key=${GEMINI_API_KEY:123123123123}
gemini.api.model=${GEMINI_API_MODEL:gemini-3-flash-preview}